kind: Deployment
apiVersion: apps/v1  
metadata:
  name:  webapp 
  namespace: #dev    
  labels:
    app: web  
spec: 
  replicas: 1     
  selector:
    matchLabels:
      app: web  
  template:
    metadata:
      name: webapp 
      labels: 
        app: web  
    spec: 
      containers:
      - name: webapp
        image: jpizzletech/advanced-spring-app:1 
        ports:
        - containerPort: 8080  

kind: Service   
apiVersion: v1  
metadata:
  name: appsvc    
spec:
  selector:
    app: web  
  type: NodePort 
  ports:
  - targetPort: 8080
    nodePort: #31000 # 30000 - 32676   
    port: 80 