kind: Deployment
apiVersion: apps/v1  
metadata:
  name:  webapp 
  namespace: #dev    
  labels:
    app: web  
spec: 
  replicas: 1     
  selector:
    matchLabels:
      app: web  
  template:
    metadata:
      name: webapp 
      labels: 
        app: web  
    spec: 
      containers:
      - name: webapp
        image: jpizzletech/advanced-spring-app:2
        ports:
        - containerPort: 8080  

